### Test power_iteration function

In [ ]:
import numpy as np  
from svd_engine import power_iteration

In [ ]:
M = np.array([[1, 2], [2, 4]])

In [ ]:
eigenvalue, eigenvector = power_iteration(M, num_iterations=100)
print(eigenvalue)
print(eigenvector)

In [ ]:
from svd_engine import deflation

In [ ]:
M_deflated = deflation(M,eigenvalue,eigenvector)

In [ ]:
print(M_deflated)

In [ ]:
from svd_engine import eigen_decompose
M = np.array([[1, 2], [2, 4]])

In [ ]:
print(eigen_decompose(M,2,100))

In [ ]:
import numpy as np  
from svd_engine import custom_svd,reconstruct_svd
M = np.array([[1, 2], [2, 4]])

In [ ]:
# Pass M and the rank k (e.g., k=2) to custom_svd
U, sigma, Vt = custom_svd(M, k=6)
M_rec = reconstruct_svd(U, sigma, Vt)

In [ ]:
# Calculate Frobenius norm of the difference matrix
loss = np.linalg.norm(M - M_rec)
# MSE
mean_loss = np.mean((M - M_rec) ** 2)
# Reconstruction loss
norm_loss = np.linalg.norm(M - M_rec) / np.linalg.norm(M)


In [ ]:
print(loss)
print(mean_loss)
print(norm_loss)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from svd_engine import custom_svd, reconstruct_svd

# 1. Create a 32x32 synthetic grayscale image (a simple 2D pattern)
x = np.linspace(-3, 3, 32)
y = np.linspace(-3, 3, 32)
X, Y = np.meshgrid(x, y)
# Create a radial wave pattern, scaled to [0, 1]
original_img = (np.sin(X**2 + Y**2) + 1) / 2.0 

# 2. Perform Custom SVD (We will keep the top 8 singular values)
k = 3
U, sigma, Vt = custom_svd(original_img, k=k)

# 3. Reconstruct the image
reconstructed_img = reconstruct_svd(U, sigma, Vt)

# 4. Display both images side-by-side
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Plot Original
axes[0].imshow(original_img, cmap='gray')
axes[0].set_title("Original 32x32 Image")
axes[0].axis("off")

# Plot Reconstructed
axes[1].imshow(reconstructed_img, cmap='gray')
axes[1].set_title(f"Reconstructed (k={k})")
axes[1].axis("off")

plt.show()


In [ ]:
import numpy as np
from svd_engine import custom_svd   # returns U, sigma, Vt

# 32×32 test matrix (the one you used in the notebook cell)
x = np.linspace(-3, 3, 32)
y = np.linspace(-3, 3, 32)
X, Y = np.meshgrid(x, y)
M = (np.sin(X**2 + Y**2) + 1) / 2.0   # values in [0,1]

# Compute *full* SVD (k = 32) to get every singular value
_, full_sigma, _ = custom_svd(M, k=32)

# Print singular values and cumulative energy
total_energy = np.sum(full_sigma**2)
cumulative = np.cumsum(full_sigma**2) / total_energy * 100

print("Singular values (descending):")
print(full_sigma.round(4))
print("\nCumulative energy (% of total) after each singular value:")
for i, pct in enumerate(cumulative, start=1):
    print(f"  k={i:2d}: {pct:6.2f}%")


In [1]:
import numpy as np
from image_pipeline import load_image

In [2]:
image = load_image('..\samples\image.jpg')


<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\lenov\AppData\Local\Temp\ipykernel_4100\3814579901.py:1: SyntaxWarning: invalid escape sequence '\s'
  image = load_image('..\samples\image.jpg')


In [3]:
print(image)

[[[0.36078431 0.34509804 0.30196078]
  [0.36078431 0.34509804 0.30196078]
  [0.36078431 0.34509804 0.30196078]
  ...
  [0.38039216 0.36078431 0.3372549 ]
  [0.38039216 0.36078431 0.3372549 ]
  [0.38039216 0.36078431 0.3372549 ]]

 [[0.36078431 0.34509804 0.30196078]
  [0.36078431 0.34509804 0.30196078]
  [0.36078431 0.34509804 0.30196078]
  ...
  [0.38039216 0.36078431 0.3372549 ]
  [0.38039216 0.36078431 0.3372549 ]
  [0.38039216 0.36078431 0.3372549 ]]

 [[0.36470588 0.34901961 0.30588235]
  [0.36470588 0.34901961 0.30588235]
  [0.36470588 0.34901961 0.30588235]
  ...
  [0.38039216 0.36078431 0.3372549 ]
  [0.38039216 0.36078431 0.3372549 ]
  [0.38039216 0.36078431 0.3372549 ]]

 ...

 [[0.26666667 0.23529412 0.19215686]
  [0.26666667 0.23529412 0.19215686]
  [0.26666667 0.23529412 0.19215686]
  ...
  [0.36470588 0.30196078 0.2       ]
  [0.36470588 0.30196078 0.2       ]
  [0.36470588 0.30196078 0.2       ]]

 [[0.26666667 0.23529412 0.19215686]
  [0.26666667 0.23529412 0.19215686]


In [4]:
print(type(image))
print(image.shape)
print(image.dtype)
print(image.min(), image.max())

<class 'numpy.ndarray'>
(4318, 7680, 3)
float64
0.0 1.0


In [5]:
from image_pipeline import split_channels
r,g,b = split_channels(image)

In [6]:
print(r)

[[0.36078431 0.36078431 0.36078431 ... 0.38039216 0.38039216 0.38039216]
 [0.36078431 0.36078431 0.36078431 ... 0.38039216 0.38039216 0.38039216]
 [0.36470588 0.36470588 0.36470588 ... 0.38039216 0.38039216 0.38039216]
 ...
 [0.26666667 0.26666667 0.26666667 ... 0.36470588 0.36470588 0.36470588]
 [0.26666667 0.26666667 0.26666667 ... 0.36470588 0.36470588 0.36470588]
 [0.26666667 0.26666667 0.26666667 ... 0.36470588 0.36470588 0.36470588]]


In [7]:
from image_pipeline import image_to_blocks, blocks_to_image
import numpy as np

# Use the 'r' channel from the previous cell
original_shape = r.shape
blocks, padded_shape = image_to_blocks(r, block_size=32)
reconstructed_r = blocks_to_image(blocks, padded_shape, original_shape, block_size=32)

# Verify if they are equal
is_equal = np.array_equal(r, reconstructed_r)
print(f"Original shape: {original_shape}")
print(f"Padded shape: {padded_shape}")
print(f"Number of blocks: {len(blocks)}")
print(f"Reconstructed matches original: {is_equal}")


Original shape: (4318, 7680)
Padded shape: (4320, 7680)
Number of blocks: 32400
Reconstructed matches original: True
